baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Portfolio"
theme = "blowfish"


[params]
colorScheme = "neon"
enableSearch = false
highlightCurrentMenuArea = true

[params.homepage]
layout = "profile"

[params.header]
layout = "fixed"

[params.footer]
showThemeAttribution = false

[params.list]
showCards = true

[params.author]
name = "Perinpagumar Munnanathan"
image = "profile.webp"

[params.article]
showAuthor = false

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "About Me"
pageRef = "about"
weight = 2

[[menu.main]]
name = "Blogs"
pageRef = "blogs"
weight = 3

[[menu.main]]
name = "Projects"
pageRef = "projects"
weight = 4

[[menu.main]]
name = "Resume"
pageRef = "resume"
weight = 5

[[main]]
name = "Links"
weight = 200

[[menu.main]]
identifier = "LinkedIn"
parent = "Links"
pre = "linkedin"
url = "https://www.linkedin.com/in/perinpagumar-munnanathan-799556253/"
weight = 1

[[menu.main]]
identifier = "GitHub"
parent = "Links"
pre = "github"
url = "https://github.com/infamousperi"
weight = 2


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
